### ISSUE TITLE
Alpha shaders invisible on OSX

### ISSUE THREAD

**Issue by catherineomega** [radiatoryang/Yarn-Weaver#11] opened 2017-10-13 16:00 UTC
First, a quick disclaimer: this is the kind of problem I remind myself is likely due to the massive amount of unsupported aftermarket hardware wedged into my 11-year-old Mac Pro, but this issue isn't something I've seen happen in other Unity games or apps so I thought I'd post it in here anyway. 

All the transparent background textures are invisible on my Mac, regardless of graphics settings or fullscreen/windowed status. This is the latest build; I will test building on my end and update this if I find anything. (Unless this ticket leads to a lot of "me too", that the correct answer is "that computer sounds sketchy as heck, what do you really expect?")

![yarn weaver 2017-10-13 08-49-37](https://user-images.githubusercontent.com/1645832/31554859-c9dcbf9e-aff3-11e7-83a9-7de6ddc520fd.jpg)

(This is a Mac Pro 1,1/GeForce 960 GTX/latest Nvidia Web Driver, 346.03.15f09/OSX 10.11.6. It works fine on my Mac Pro 3,1/Radeon 5770/OSX 10.11.6.

**Comment by radiatoryang** [comment] 2017-10-14 18:49
That does indeed sound like a very interesting setup... there's a few things I can try (adjusting the UI graphics, updating to Unity 2017.2, disabling Metal support) but that's pretty much all that's possible from my end. Will send you a hotfix build soon, if you want to try it out?

**Comment by catherineomega** [comment] 2017-10-14 23:05
That sounds great, thanks! A little Googling suggests it's likely the Metal support. If it's not that, I'm happy to try adjusting the shader on my end, see if that works?

--

**Comment by catherineomega** [comment] 2017-10-14 23:53
Oh, huh. Maybe I spoke too soon. It seems like it thinks my GTX 960 can handle Metal?
![screen shot 2017-10-14 at 4 52 14 pm](https://user-images.githubusercontent.com/1645832/31580299-24233ffc-b100-11e7-90b8-7c00fef1199f.png)

**Comment by radiatoryang** [comment] 2017-10-15 03:48
Well, the issue is more that your GPU thinks it can handle Metal, but then there's secretly a glitch or a problem... in the past, I've had to disable Metal support to force OSX to use OpenGL instead (which apparently has fewer bugs)... can you try this build, v0.1.5b on your GTX960 machine?: https://github.com/radiatoryang/Yarn-Weaver/releases/tag/v0.1.5b

**Comment by catherineomega** [comment] 2017-10-15 14:26
Oh right, that makes sense. And yes, as you can see, that was the solution. Thanks for your help!

![yarn weaver 2017-10-15 07-24-49](https://user-images.githubusercontent.com/1645832/31585638-17fa2ab8-b17a-11e7-9409-ca16ed1fe73d.jpg)

**Comment by radiatoryang** [comment] 2017-10-18 16:20
Great, awesome! Closing this issue (https://github.com/radiatoryang/Yarn-Weaver/releases/tag/v0.1.5b) and will merge it into the main master for v0.1.6 since I don't think any other OSX users will miss using Metal either

**Closed as completed by radiatoryang** 2017-10-18 16:20 UTC
